### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by mikasolomi** [mikasolomi/homepage#6]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by Mairiaa** [comment]
Кіт Мурко, фулл-стек розробник з неабияким досвідом, який будує точні, адаптивні, швидкі, зручні в користуванні середовища, які гарно виглядають та добре виконують свої завдання. Улюбленими технологіями вважає ReMau t та C#Mau. Людською говорить із смішним акцентом (мишачою теж).
