### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by mikasolomi** [mikasolomi/homepage#7]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by Mairiaa** [comment]
zhannabadoeva.com
@zhanna_badoeva_shoes
https://www.youtube.com/channel/UCFGe3bs70DY3bpENODw3Ftg
