### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by mikasolomi** [mikasolomi/homepage#8]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by Mairiaa** [comment]
У 2011 році разом з Аланом Бадоєвим була ведучою тревел-шоу «Орел і Решка»; За роки подорожей об'їздила багато країн, побачила світ. Пішла з проєкту в 2012 році. Причину такого вчинку пояснила втомою: жінка жила проєктом, жертвувала сім'єю, щороку 9 з 12 місяців подорожувала. Програма була сенсом її життя.

Після першого проєкту стала суддею на проєкті «МастерШеф». Цим її амбіції не обмежилися, почався новий проєкт — «Не зупиняй мене» на телеканалі Інтер. У своєму новому шоу працювала разом з Дмитром Коляденком.

Пізніше вела проєкт «Битва салонів» на телеканалі «П'ятниця!».

У 2015 році разом з Андрієм Бідняковим, Лесею Нікітюк і Регіною Тодоренко знялася в кліпі Світлани Лободи «Пора домой».

Має свій власний бізнес — аудіо-відеосалон.
