### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by mikasolomi** [mikasolomi/homepage#9]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by Mairiaa** [comment]
Подобається: спати, їсти, муркати, вдавати байдужого.
Не подобається: нові знайомства, вегетеріанці, відсутність корму.
Сильні сторони: пухнастий, милий, вмію тихо переміщатися.
Слабкі сторони: не вмію читати, писати, жити без улюбленого корму :(
Хобі: жити- це моє хобі
